/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: "doc", id: "intro" },
    { type: "autogenerated", dirName: "tutorial-basics" },
    { type: "autogenerated", dirName: "tutorial-extras" },
  ],
  openApiSidebar: [
    {
      type: "category",
      label: "API v2",
      link: {
        type: "generated-index",
        title: "API v2",
        description: "OpenFoodFacts API v2.",
        slug: "/category/api-v2",
      },
      items: require("./docs/api-v2/sidebar.js"),
    },
    {
      type: "category",
      label: "API v3",
      link: {
        type: "generated-index",
        title: "API v3",
        description: "OpenFoodFacts API v3.",
        slug: "/category/api-v3",
      },
      items: require("./docs/api-v3/sidebar.js"),
    },
  ],
};

export default sidebars;
